<?php include_once('header.php'); ?>
<section class="container-fluid mt-10 rickshaw-section text-center">
        <div class="container">
            <h1 class="display-2">SCIENCE & TECHNOLOGY ENTREPRENEURSHIP DEVELOPMENT (STED) PROJECT</h1>
            <p class="pt-3">Promoting & grooming of entrepreneurs for assembling the slow-moving vehicles!</p>
            <p> <i class="fas fa-arrow-right"></i> Science & Technology Entrepreneurship Development (STED) Project is an ambitious initiative of the Department of Science & Technology, Government of India to bring about a socio-economic development of an area through the intervention of science & technology. It aims at inculcating strong entrepreneurial orientation in people that will result in effective utilization of resources both human and material of a region besides generating opportunities for employment and creation of wealth. One of the key focused areas of STED is to raise the socio-economic level of the economically weaker sections of the population in the region by enhancing their earning potential through self-employment. This is done through by helping them to set up micro-enterprises through a process of empowering them with technical knowledge and skills besides business related skills.</p>
            <p> <i class="fas fa-arrow-right"></i> As an executing agency under this prestigious project, Centre for Rural Development (CRD) has to undertake and operate the project by promoting Micro-entrepreneurs for production of Slow-moving vehicles replicating the existing Rickshaw Bank of CRD as the model enterprise, as well as for conducting Research & Design innovations of the existing slow-moving vehicles by engaging qualified professionals.</p>
            <p> <i class="fas fa-arrow-right"></i> CRD under the STED Project will select, train and support 80(eighty) aspiring micro-entrepreneurs in 80(eighty) Districts covering 16(sixteen) states including Assam, Bihar, Chattisgarh, Gujarat, Haryana, Jharkhand, Manipur, Madhya Pradesh, Orissa, Punjab, Rajasthan, Tamil Nadu, Tripura, Uttarakhand, Uttar Pradesh and West Bengal, within a period of 4(four) years starting from May 2009, providing them all kinds of guidance including skill development trainings for setting up small industrial units in order to independently assemble/manufacture eco-friendly slow-moving vehicles like Cycle Rickshaw, Food Cart, Vegetable & Fruits Cart, Garbage Cart, Fish Carts, Momo Cart etc.</p>
            <p> <i class="fas fa-arrow-right"></i> The target group would essentially be unemployed youth who may or may not possess necessary skill to launch a micro-unit but have the necessary desire and aptitude for such venture.</p>
            <p> <i class="fas fa-arrow-right"></i> The operation for first year has been started in Assam, wherein 17 districts are being targeted and STED staff started their screening process of entrepreneurs and grooming their enterprises.
            Progress during this financial year has been:</p>
             <p> <i class="fas fa-arrow-right"></i> An extensive study and documentation of the working methodology of the existing Rickshaw Bank project of CRD has been accomplished on the basis of keen observation and interaction with the existing staff of the said project. Apart from technical aspect, special study had been made on the financial and social aspects of the enterprise and all its stakeholders. The outcome of these studies was a thorough analysis of the overall improvisations necessary for promotion of the Rickshaw Bank model under STED Project for creation of new Micro Entrepreneurs. Finally, a Process Manual has been prepared as the guiding and reference book for implementation of the various stages of the project.</p>
             <p> <i class="fas fa-arrow-right"></i> In the meantime, under the STED Project, a unique initiative for harnessing traditional wisdom and natural skills of local rural innovators has been undertaken. As part of this initiative, technical collaboration with indigenous innovators for design innovations of slow moving vehicles has been made, and within a short span time, a new design using 2(two) cranks and 2(two) Chain-systems has been developed together with a gear system, which could be effortlessly introduced in the existing models of the Rickshaw Bank for enhancing its efficiency.</p>
             <p> <i class="fas fa-arrow-right"></i> The Project also utilized the unique service of a British Environmental Intern named Ms Tess Joyce from Kingston University, London. She joined the STED Project team, and during July-August/2009, helped the team in collecting information regarding environmental issues as well as workers’ safety standards maintained at the present Rickshaw Bank workshop. It is significant that during the preparation of the environmental model, support from the Centre for Environment of Indian Institute of Technology, Guwahati, had also been availed, and extensive research had been made for reference to the highest standard of environmental practices maintained all over the world in relation to micro enterprise workshops. Ultimately, the new Environmental Report became extraordinary and unique, because, here the internationally recognized EMAS standard had been adapted, while localized need and problems specific to India have also been incorporated. This environmental standard model had been already incorporated within the STED Process Manual for its practical utility.
            </p>
            <p> <i class="fas fa-arrow-right"></i> The project team has also started ‘dissemination of project information’ at different townships viz. Nalbari, Morigaon, Nagaon, Goalpara. Barpeta, Darrang, Bongaigaon, Sivasagar, Jorhat, Golaghat, Diburugarh, Tinisukia in Assam through its different branch/ field level units and ‘rapport building’ with different mainstream institutes viz. banks, DICC etc. STED team had also availed the opportunities of highlighting its objectives before stake-holders, other organizations involved in similar activities, as well as development agencies and scientific collaborators. Efforts were given to explore the various possibilities of technological, social and financial collaborations with other similar initiatives. The interaction with print, audio and visual media during these programmes had also enriched the profile of the project. These additional efforts of the STED team managed to create additional linkages with other NGOs and Government Agencies for future success of the Project.</p>
            <p> <i class="fas fa-arrow-right"></i> A model Bankable Project was also prepared in order to help the entrepreneurs for credit linkage from banks or other financial institutes.</p>
            <p> <i class="fas fa-arrow-right"></i> By the end of the year, a total of 11 entrepreneurs have been screened and groomed for taking up their own enterprise. Already 5 entrepreneurs in different districts viz. Morigaon, Goalpara, Baksa, Nalbari, Bongaigaon have started their enterprises.</p>
        </div>
    </section>
<?php include_once('footer.php'); ?>